###Create a patient
POST http://localhost:8080/patients
Content-Type: application/json

{
  "name" : "John Doe2",
  "email" : "test3@example.com",
  "address" : "23 Burr Street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###