###Create a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Checkka billing",
  "email" : "ka@example.com",
  "address" : "23 Burr Street",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"
}

###